[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1_000_000
solc = "0.8.28"
viaIR = true
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
